Repository mlswg/mls-protocol, pull requests merged in 2019-12, with the labels that each got.

#257 Make clear that Commits are responsible for FS and PCS
  draft-ietf-mls-protocol.md
Labels: editorial

#254 Initial work to use CIK in leaves
  draft-ietf-mls-protocol.md
Labels: functionality, security, work in progress

#253 Initial version of the Tree of Signature
  draft-ietf-mls-protocol.md
Labels: ready to merge, security

#265 Align spec text with implementation
  draft-ietf-mls-protocol.md
Labels: bug, work in progress
