Repository mlswg/mls-protocol, pull requests merged in 2020-01, with the labels that each got.

#263 Change special values to structed types for external senders
  draft-ietf-mls-protocol.md
Labels: discussion

#292 Editorial on top of PR #278
  draft-ietf-mls-protocol.md
Labels: editorial

#246 Bugfixes in ClientInitKey, Commit, and Welcome
  draft-ietf-mls-protocol.md
Labels: today! (?)

#247 Welcome confirmation and key derivation
  draft-ietf-mls-protocol.md
Labels: enhancement, security
