Repository mlswg/mls-protocol, pull requests merged in 2020-03, with the labels that each got.

#310 Fix identation and remove some vestigial stuff from the key schedule.
  draft-ietf-mls-protocol.md
Labels: editorial

#283 Use the same ratchet for Handshake and Application keys
  draft-ietf-mls-protocol.md
Labels: discussion, privacy, ready to merge, security

#311 Review of section 7.
  draft-ietf-mls-protocol.md
Labels: editorial

#275 Mandate expiration of ClientInitKeys and presence of some extensions
  draft-ietf-mls-protocol.md
Labels: enhancement, ready to merge, security

#296 Flesh out the extensions story
  draft-ietf-mls-protocol.md
Labels: editorial, functionality, security
