Repository mlswg/mls-protocol, pull requests merged in 2020-02, with the labels that each got.

#285 Get rid of ignored proposals.
  draft-ietf-mls-protocol.md
Labels: security, today! (?)

#286 Editorial: Unclear that Commits always include an Update/refreshes the CIK for the committer.
  draft-ietf-mls-protocol.md
Labels: editorial, today! (?)

#287 Switch to signing strategy using one signature per leaf.
  draft-ietf-mls-protocol.md
Labels: discussion, enhancement, performance, ready to merge, security

#294 Re-define direct path to not include the leaf.
  draft-ietf-mls-protocol.md
Labels: today! (?)

#295 Use path secret instead of full DirectPath
  draft-ietf-mls-protocol.md
Labels: today! (?)

#306 Typos
  draft-ietf-mls-protocol.md
Labels: editorial

#305 Update HKDFLabel variable to match naming conventions
  draft-ietf-mls-protocol.md
Labels: ? invalid, editorial
